apiVersion: rating.alterway.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-carbon_simulation_FR_1
  namespace: rating
spec:
  carbon_factor: 0.28
  metric: ((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))
    + (ceil(sum(node_cpu_core_throttles_total) * max(node_cpu_package_throttles_total)))
    + sum(prometheus_remote_storage_samples_in_total)) * 220/1000 *0.28 / 1000000
  metric_name: carbon_simulation_FR_1
  template_name: carbon_simulation
  timeframe: 3600s
