version: '3'
services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.33.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Corrected volume mapping
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring_net  # Add this line


  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1  # Specify the desired version here
    container_name: node-exporter
    volumes:
      - /etc/prometheus/node_exporter.yml:/etc/prometheus/node_exporter.yml  # Mount the node_exporter configuration file
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--collector.textfile.directory=/etc/prometheus"   # Specify the path to the configuration file
    ports:
      - "9100:9100"
    networks:
      - monitoring_net  # Add this line

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    
    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus
   
    networks:
      - monitoring_net  # Add this line
    
 


  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=mypassword  # Replace with your desired password
      - POSTGRES_DB=mydatabase  # Replace with your desired database name
      - POSTGRES_USER=myuser  # Replace with your desired username
      
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/14/main:/var/lib/postgresql/14/main
    networks:
      - monitoring_net


   

networks:
  monitoring_net:
    driver : bridge  # Define the user-defined network


volumes:
  grafana-data:
  timescaledb_data:
