apiVersion: rating.smile.fr/v1
kind: RatingRuleTemplate
metadata:
  name: rating-rule-template-carbon-emission
  namespace: rating
  #namespace: {{ .Release.Namespace }}
spec:
  query_name: carbon_simulation
  query_group: 3600s
  query_template: "((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))
    + (ceil(sum(prometheus_remote_storage_samples_in_total) * max(prometheus_remote_storage_samples_in_total)))
    + sum(prometheus_remote_storage_samples_in_total)) *{carbon_factor} / 1000000" 


