apiVersion: rating.alterway.fr/v1
kind: RatingRuleTemplate
metadata:
  name: rating-rule-template-carbon-emission
  namespace: rating
  #namespace: {{ .Release.Namespace }}
spec:
  query_name: carbon_simulation
  query_group: 3600s
  query_template: "((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024))) + (ceil(sum(node_cpu_core_throttles_total)
          * max(node_cpu_package_throttles_total))) + sum(prometheus_remote_storage_samples_in_total)) * 220/1000 *{carbon_factor} / 1000000" 

