{
 "title": "Carbon Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "carbon_simulation_EU (KgCO2eq)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "expr": "((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024))) + (ceil(sum(node_cpu_core_throttles_total)* max(node_cpu_package_throttles_total))) + sum(prometheus_remote_storage_samples_in_total)) * 220/1000 * 0.238 / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "carbon_simulation_Germany (KgCO2eq)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "expr": "((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024))) + (ceil(sum(node_cpu_core_throttles_total)* max(node_cpu_package_throttles_total))) + sum(prometheus_remote_storage_samples_in_total)) * 220/1000 * 0.253 / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "carbon_simulation_France (KgCO2eq)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "expr": "((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024))) + (ceil(sum(node_cpu_core_throttles_total)* max(node_cpu_package_throttles_total))) + sum(prometheus_remote_storage_samples_in_total)) * 220/1000 * 0.28 / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "carbon_simulation_Italy (KgCO2eq)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    {
     "expr": "((ceil(sum(node_memory_Active_anon_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024))) + (ceil(sum(node_cpu_core_throttles_total)* max(node_cpu_package_throttles_total))) + sum(prometheus_remote_storage_samples_in_total)) * 220/1000 * 0.297 / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}