---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleInstance
metadata:
  creationTimestamp: "2021-08-19T23:06:12Z"
  name: rating-rule-instance-aws-cost
  namespace: rating
  ownerReferences:
  - apiVersion: charts.helm.k8s.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rating
    name: rating
    uid: 5e8bf7fd-04dc-4786-8745-f2e690c1029a
  resourceVersion: "74473530"
  selfLink: /apis/rating.alterway.fr/v1/namespaces/rating/ratingruleinstances/rating-rule-instance-node-cost-simulation-aks-a8
  uid: 887ae58c-025e-41c6-8761-ad47960d36ce
spec:
  cpu: "1"
  memory: "1"
  price: "0.5"
  timeframe: 3600s
    
  metric: "((ceil(sum(node_memory_MemTotal_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/1 > 
          (ceil(sum(node_memory_MemTotal_bytes) * max(node_memory_MemTotal_bytes))) /1 or 
          (ceil(sum(node_memory_MemTotal_bytes) * max(node_memory_MemTotal_bytes)))/1) * 0.5"
  name: aks-cost

  #((ceil(sum(node_memory_MemTotal_bytes) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/1 > (ceil(sum(node_memory_MemTotal_bytes) * max(node_memory_MemTotal_bytes))) /1 or (ceil(sum(node_memory_MemTotal_bytes) * max(node_memory_MemTotal_bytes)))/1) * 0.5


